# application: sports-heroes #PRODUCTION dont break!!!
application: dev-sports-heroes #Development site
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version: 1-1-5-templates1
=======
version: 1-1-3-datam
>>>>>>> parent of e079809... Ability to add entrypoint URLs for SPORT and COUNTRY
=======
version: 1-1-3-datam
>>>>>>> parent of e079809... Ability to add entrypoint URLs for SPORT and COUNTRY
=======
version: 1-1-3-datam
>>>>>>> parent of e079809... Ability to add entrypoint URLs for SPORT and COUNTRY
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /admin/.*
  script: main.app
  login: required
#NEXT main.py

- url: .*
  script: main.app
#NEXT main.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
