application: sports-heroes
version: 1-0-6-masters
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /admin/.*
  script: main.app
  login: required
#NEXT main.py

- url: .*
  script: main.app
#NEXT main.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
