# application: sports-heroes #PRODUCTION dont break!!!
application: dev-sports-heroes #Development site
<<<<<<< HEAD
<<<<<<< HEAD
version: 1-1-3-datam
=======
version: 1-1-4-urls
>>>>>>> parent of a6a652a... oops
=======
version: 1-1-4-urls
>>>>>>> parent of a6a652a... oops
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /admin/.*
  script: main.app
  login: required
#NEXT main.py

- url: .*
  script: main.app
#NEXT main.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
